### ISSUE TITLE
Rebase request

### ISSUE THREAD

**Issue by FlyGoat** [loongson-community/binutils-gdb#2]
Hi toolchain developers
Binutils have released 2.30 recently. According my tests, all changes made by Loongson-Community work perfectly under 2.30.
So please create a new branch for 2.30 and rebase all the commits to 2.30.
Thanks.

**Comment by xiangzhai** [comment]
@FlyGoat you are welcome! @heiher please merge upstream/binutils-2_30-branch and I am migrating the commits from https://github.com/loongson-community/binutils-gdb/commit/18b0a05fbf15a63abc9e7b6ed3674af9a53898b4 to 2.30 branch. Thanks!

**Comment by xiangzhai** [comment]
Hi @FlyGoat @heiher please review my rebase https://github.com/xiangzhai/binutils-gdb/commit/c72829c57637b18abd6b6bb738d49a0078c6220b Thanks a lot!

**Comment by xiangzhai** [comment]
Already merged by upstream? https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=8095d2f70e1a982c006f306be1a9e1c892758914
